#!/bin/bash
set -euo pipefail

if [[ "$1" == "list" ]]; then
    sxm --list-channels
elif [[ "$1" == "stop" ]]; then
    disown &>/dev/null
    echo "HTTP Server & VLC have been shut down."
else
    if [[ ! $(jobs) ]]; then
        sxm --host $SXM_HOST --region $SXM_REGION --port $SXM_PORT &>/dev/null &
        /Applications/VLC.app/Contents/MacOS/VLC http://$SXM_HOST:$SXM_PORT/$1.m3u8 &>/dev/null &
    else
        /Applications/VLC.app/Contents/MacOS/VLC vlc://quit &>/dev/null
        /Applications/VLC.app/Contents/MacOS/VLC http://$SXM_HOST:$SXM_PORT/$1.m3u8 &>/dev/null &
    fi
fi